name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.4

      - name: Set up Poetry environment
        run: |
          poetry cache clear PyPI --all
          poetry install --no-root

      - name: Run ruff
        run: |
          poetry run ruff check .

      - name: Run ruff format
        run: |
          poetry run ruff format --check .

      - name: Run mypy
        run: |
          poetry run mypy --show-error-codes .

      - name: Run tests
        run: |
          poetry run pytest
